---
title: "Homework Assignment Two"
subtitle: "Exploring patterns of environmental justice"
author: Amanda G. Overbye
date: last-modified
execute: 
  eval: true
format:
  html:
    toc: true
editor_options: 
  chunk_output_type: console
---

```{r}
# Load in libraries
library(here)
library(tidyverse)
library(sf)
library(tmap)
library(ggplot2)
library(cowplot)
```


## Part 1: Legacy of redlining in current environmental (in)justice

```{r}
# Read in data

# Read in ejscreen
ejscreen <- sf::st_read(here::here("data","ejscreen","EJSCREEN_2023_BG_StatePct_with_AS_CNMI_GU_VI.gdb"))

# Filter California from ejscreen
cali <- ejscreen %>%
  dplyr::filter(ST_ABBREV == "CA")

# Filter Los Angeles County from cali
la_county <- cali %>%
  dplyr::filter(CNTY_NAME %in% c("Los Angeles County"))

# Read in mapping inequality 
la_map_ineq <- st_read(here::here("data", "mapping-inequality", "mapping-inequality-los-angeles.json"))

# Read in bird data 
bird_obs <- st_read(here::here("data", "gbif-birds-LA", "gbif-birds-LA.shp"))

```


```{r}
#color = "#547c79ff"
full_la <- tm_shape(cali, bbox = "Los Angeles County") +
  tm_polygons() +
tm_shape(la_county) +
  tm_polygons() +
  tm_shape(la_map_ineq) +
  tm_polygons(col = "grade") +
  tm_layout(legend.show = FALSE)
```

```{r}
full_la
```


```{r}
ineq_bbox <- st_bbox(la_map_ineq)

```

```{r}
mini_la <- tm_shape(cali, bbox = ineq_bbox) +
  tm_polygons() +
tm_shape(la_county) +
  tm_polygons() +
  tm_shape(la_map_ineq) +
  tm_polygons(col = "grade") +
```

```{r}
print(mini_la)
```


```{r}
main_tmap <- tmap_grob(mini_la)

sub_tmap <- tmap_grob(full_la)
```

```{r}
inset_la <- ggdraw() +
  draw_plot(main_tmap) +
  draw_plot(sub_tmap, height = 0.3,
    x = -0.3
  )
```

```{r}
print(inset_la)
```

# ADD A WARNING ABOUT WHETHER OR NOT THEY ARE THE SAME CRS

```{r}
# Ensure la_map_ineq and la_county are using the same la_map_ineq crs system
la_map_ineq <- st_transform(la_map_ineq, crs = st_crs(la_county))
```

```{r}
# Join la_county and la_map_ineq with st_intersects()
joined_la <- st_join(la_county, la_map_ineq, join = st_intersects)
```


```{r}
# Create table of percent in each HOLC group
HOLC_percent <- joined_la %>%
  group_by(grade) %>%
  summarise(count = n()) %>%
  mutate(HOLC_percent = (count / sum(count)) * 100)
  
```

```{r}
# Print table
print(HOLC_percent)
```

```{r}
# Get mean values for percentage low income, PM2.5 percentiles, and low life expediency percentiles
sum_current_conditions <- joined_la %>%
  group_by(grade) %>%
  summarise( 
    low_income_mean = (mean(LOWINCPCT, na.rm = TRUE) * 100),
    pm2_mean = mean(P_PM25, na.rm = TRUE),
    life_exp_mean = mean(P_LIFEEXPPCT, na.rm = TRUE))
```

```{r}
# Create graph for sum_current_conditions
ggplot(data = sum_current_conditions, aes(x = grade, y = pm2_mean)) +
  geom_col(fill = "#547c79ff") +
  labs(title = "Mean PM 2.5 Percentile by HOLC Grade", 
       x = "HOLC Grade", 
       y = "Mean Life PM 2.5 Percentile")

ggplot(data = sum_current_conditions, aes(x = grade, y = low_income_mean)) +
  geom_col() +
  labs(title = "Mean Low Income Percentile by HOLC Grade", 
       x = "HOLC Grade", 
       y = "Mean Percent Low Income")

ggplot(data = sum_current_conditions, aes(x = grade, y = life_exp_mean)) +
  geom_col() +
  labs(title = "Mean Life Expectancy Percentile by HOLC Grade", 
       x = "HOLC Grade", 
       y = "Mean Life Expectancy Percentile")
```


## Part 2: Legacy of redlining in biodiversity observations

```{r}

```

# ADD A WARNING ABOUT WHETHER OR NOT THEY ARE THE SAME CRS

```{r}
bird_obs <- st_transform(bird_obs, crs = st_crs(la_county))
```


```{r}
la_birds <- st_join(la_map_ineq, bird_obs, join = st_intersects)
```


```{r}
birds_obs_percent <- la_birds %>%
  group_by(grade) %>%
  summarise(obs_count = n()) %>%
  mutate(percentage = (obs_count / sum(obs_count)) * 100)
```

```{r}
# Create col chart of the percent of birds in each grade
ggplot(data = birds_obs_percent, aes(x = grade, y = percentage)) +
  geom_col()
```

```{r}
tm_shape(cali, bbox = "Los Angeles County") +
  tm_polygons() +
tm_shape(la_county) +
  tm_polygons() +
  tm_shape(la_map_ineq) +
  tm_polygons(col = "grade") +
  tm_layout(legend.show = FALSE) +
  tm_shape(la_birds) +
  tm_polygons()
```

